name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # daily update
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: DeveloperSarim

          template: classic
          base: header, activity, community, repositories

          # Languages
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_limit: 8

          # Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: detailed

          # Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Follow-ups
          plugin_followup: yes
